name: Precommit

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build SCP
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up JDK 8
      run: sudo apt-get install -y openjdk-8-jdk

    - name: Build SCP library
      run: python3.10 scripts/build.py -c lib

    - name: Build SCP library documentation
      run: python3.10 scripts/build.py -c doc
