name: Precommit

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build SCP
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build SCP library
      run: echo "run SCP build..."
